### ISSUE TITLE
Feat: Brand (multi color) mode

### ISSUE THREAD

**Issue by Dangoo** [sinnerschrader/patternplate-client#165]
Patternplate can display patterns designed for one single brand/client.
But sometimes it is necessary to build a white label solution and display some occurrences.
What about adding a switch to enable testing of different versions of the patterns?

**Comment by marionebl** [comment]
Basically `patternplate-server` already supports this via the environments functionality (documentation pending). 

We could devise a simple interface (GET-parameters?) for the`patternplate-client` to force a given environment on the patterns it requests from `patternplate-server`. 

The bulk of the work for this would have to be done in [routes/pattern.js](https://github.com/sinnerschrader/patternplate-server/blob/master/source/application/routes/pattern.js).

I'm not sure where to place this in the frontend, any suggestions?

/cc @levito @KnisterPeter @felabr

**Comment by Dangoo** [comment]
I'd suggest either globally on the place of the former download select or directly in the head of each pattern (Toolbar planed for 1.0 required)

**Comment by marionebl** [comment]
I'm strongly in favor of locating this at individual patterns as environment config essentially applies to each pattern individually.

**Comment by KnisterPeter** [comment]
I would favor it in the toolbar as well

**Comment by marionebl** [comment]
This issue was moved to sinnerschrader/patternplate#27
